service: bf-messages

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  upload:
    handler: messages/upload.upload
    events:
      - http:
          path: messages/upload
          method: post
          cors: true

  create:
    handler: messages/create.create
    events:
      - http:
          path: messages
          method: post
          cors: true

  list:
    handler: messages/list.list
    events:
      - http:
          path: messages
          method: get
          cors: true

  get:
    handler: messages/get.get
    events:
      - http:
          path: messages/{id}
          method: get
          cors: true

  update:
    handler: messages/update.update
    events:
      - http:
          path: messages/{id}
          method: put
          cors: true

  delete:
    handler: messages/delete.delete
    events:
      - http:
          path: messages/{id}
          method: delete
          cors: true

resources:
  Resources:
    MessagesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
